In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:80% !important; }</style>"))

import json
import pandas as pd
from datetime import date, timedelta, datetime

In [2]:
with open("caly_2016.json", "r") as f:
    res = json.load(f)

In [3]:
cols = pd.read_csv('../data/exchange_rates.csv', sep=';').columns

In [4]:
df = pd.DataFrame(columns=cols)

for day in res:
    timestamp = datetime.strptime(list(day.keys())[0], "%Y-%m-%d").strftime("%d.%m.%Y")
    val = day[list(day.keys())[0]]
    
    usdeur = val['USDEUR']
    usdgbp = val['USDGBP']
    usdchf = val['USDCHF']
    
    eurusd = 1 / val['USDEUR']
    eurgbp = val['USDGBP'] / val['USDEUR']
    eurchf = val['USDCHF'] / val['USDEUR']
    
    gbpusd = 1 / val['USDGBP']
    gbpeur = val['USDEUR'] / val['USDGBP']
    gbpchf = val['USDCHF'] / val['USDGBP']
    
    chfusd = 1 / val['USDCHF']
    chfeur = val['USDEUR'] / val['USDCHF']
    chfgbp = val['USDGBP'] / val['USDCHF']
    
    usdpln = val['USDPLN']
    eurpln = val['USDPLN'] / val['USDEUR']
    gbppln = val['USDPLN'] / val['USDGBP']
    chfpln = val['USDPLN'] / val['USDCHF']
    
    df.loc[len(df)] = [timestamp, usdeur, usdgbp, usdchf, eurusd, eurgbp, eurchf, gbpusd, gbpeur, gbpchf, chfusd, chfeur, chfgbp, usdpln, eurpln, gbppln, chfpln]

In [5]:
df

,timestamp,USD-EUR,USD-GBP,USD-CHF,EUR-USD,EUR-GBP,EUR-CHF,GBP-USD,GBP-EUR,GBP-CHF,CHF-USD,CHF-EUR,CHF-GBP,USD-PLN,EUR-PLN,GBP-PLN,CHF-PLN
0,01.01.2016,0.920961,0.678607,0.999570,1.085822,0.736847,1.085355,1.473607,1.357135,1.472973,1.000430,0.921357,0.678899,3.928846,4.266029,5.789575,3.930536
1,02.01.2016,0.920862,0.677491,1.001164,1.085939,0.735714,1.087203,1.476034,1.359224,1.477752,0.998837,0.919791,0.676703,3.936752,4.275073,5.810781,3.932175
2,03.01.2016,0.920289,0.678475,1.000194,1.086615,0.737241,1.086826,1.473894,1.356408,1.474180,0.999806,0.920110,0.678343,3.934986,4.275816,5.799751,3.934223
3,04.01.2016,0.923285,0.679566,1.001684,1.083089,0.736031,1.084913,1.471527,1.358639,1.474005,0.998319,0.921733,0.678424,3.961150,4.290279,5.828941,3.954491
4,05.01.2016,0.930028,0.681320,1.006762,1.075236,0.732580,1.082507,1.467739,1.365038,1.477664,0.993283,0.923781,0.676744,3.994319,4.294837,5.862618,3.967491
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,27.12.2016,0.955701,0.814620,1.027670,1.046352,0.852380,1.075305,1.227566,1.173186,1.261533,0.973075,0.929969,0.792686,4.202401,4.397192,5.158726,4.089251
362,28.12.2016,0.959597,0.817960,1.028090,1.042104,0.852399,1.071377,1.222554,1.173159,1.256895,0.972677,0.933378,0.795611,4.228700,4.406746,5.169813,4.113161
363,29.12.2016,0.945498,0.813540,1.016480,1.057644,0.860435,1.075074,1.229196,1.162202,1.249453,0.983787,0.930169,0.800350,4.168016,4.408276,5.123308,4.100441
364,30.12.2016,0.950404,0.810260,1.017504,1.052184,0.852543,1.070602,1.234172,1.172962,1.255775,0.982797,0.934054,0.796321,4.182038,4.400274,5.161353,4.110095
365,31.12.2016,0.950404,0.810260,1.017804,1.052184,0.852543,1.070917,1.234172,1.172962,1.256145,0.982507,0.933779,0.796086,4.182038,4.400274,5.161353,4.108883

In [6]:
df.to_csv("caly_2016.csv", index=None, sep=';')