In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:80% !important; }</style>"))

import json
import pandas as pd
from datetime import date, timedelta, datetime

In [21]:
with open("koniec_2017.json", "r") as f:
    res = json.load(f)

In [22]:
cols = pd.read_csv('../data/exchange_rates.csv', sep=';').columns

In [23]:
df = pd.DataFrame(columns=cols)

for day in res:
    timestamp = datetime.strptime(list(day.keys())[0], "%Y-%m-%d").strftime("%d.%m.%Y")
    val = day[list(day.keys())[0]]
    
    usdeur = val['USDEUR']
    usdgbp = val['USDGBP']
    usdchf = val['USDCHF']
    
    eurusd = 1 / val['USDEUR']
    eurgbp = val['USDGBP'] / val['USDEUR']
    eurchf = val['USDCHF'] / val['USDEUR']
    
    gbpusd = 1 / val['USDGBP']
    gbpeur = val['USDEUR'] / val['USDGBP']
    gbpchf = val['USDCHF'] / val['USDGBP']
    
    chfusd = 1 / val['USDCHF']
    chfeur = val['USDEUR'] / val['USDCHF']
    chfgbp = val['USDGBP'] / val['USDCHF']
    
    usdpln = val['USDPLN']
    eurpln = val['USDPLN'] / val['USDEUR']
    gbppln = val['USDPLN'] / val['USDGBP']
    chfpln = val['USDPLN'] / val['USDCHF']
    
    df.loc[len(df)] = [timestamp, usdeur, usdgbp, usdchf, eurusd, eurgbp, eurchf, gbpusd, gbpeur, gbpchf, chfusd, chfeur, chfgbp, usdpln, eurpln, gbppln, chfpln]

In [24]:
df

,timestamp,USD-EUR,USD-GBP,USD-CHF,EUR-USD,EUR-GBP,EUR-CHF,GBP-USD,GBP-EUR,GBP-CHF,CHF-USD,CHF-EUR,CHF-GBP,USD-PLN,EUR-PLN,GBP-PLN,CHF-PLN
0,27.03.2017,0.920505,0.79631,0.985800,1.086360,0.865079,1.070934,1.255792,1.155963,1.237960,1.014405,0.933764,0.807780,3.910597,4.248317,4.910898,3.966927
1,28.03.2017,0.924298,0.80516,0.992130,1.081902,0.871104,1.073388,1.241989,1.147968,1.232215,1.007932,0.931630,0.811547,3.919799,4.240839,4.868348,3.950893
2,29.03.2017,0.929402,0.80373,0.996640,1.075961,0.864782,1.072345,1.244199,1.156361,1.240018,1.003371,0.932535,0.806440,3.926397,4.224649,4.885219,3.939634
3,30.03.2017,0.935497,0.80145,1.000370,1.068951,0.856710,1.069346,1.247738,1.167256,1.248200,0.999630,0.935151,0.801154,3.940404,4.212097,4.916594,3.938947
4,31.03.2017,0.937304,0.79713,1.003041,1.066890,0.850450,1.070134,1.254501,1.175848,1.258315,0.996968,0.934462,0.794713,3.961304,4.226275,4.969458,3.949294
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,27.12.2017,0.840097,0.74606,0.985910,1.190339,0.888064,1.173567,1.340375,1.126045,1.321489,1.014291,0.852103,0.756722,3.519602,4.189519,4.717586,3.569902
276,28.12.2017,0.837301,0.74405,0.978680,1.194314,0.888629,1.168851,1.343996,1.125329,1.315342,1.021784,0.855541,0.760259,3.499398,4.179379,4.703176,3.575630
277,29.12.2017,0.833204,0.74062,0.974090,1.200186,0.888882,1.169089,1.350220,1.125009,1.315236,1.026599,0.855367,0.760320,3.480404,4.177133,4.699311,3.572980
278,30.12.2017,0.833204,0.74062,0.973804,1.200186,0.888882,1.168746,1.350220,1.125009,1.314850,1.026901,0.855618,0.760543,3.480404,4.177133,4.699311,3.574029
279,31.12.2017,0.833398,0.73998,0.974639,1.199907,0.887907,1.169476,1.351388,1.126244,1.317115,1.026021,0.855084,0.759235,3.482404,4.178561,4.706079,3.573019

In [25]:
df.to_csv("koniec_2017.csv", index=None, sep=';')